const fs = require('fs');
let code = fs.readFileSync('src/pages/ContatoPage.tsx', 'utf8');

code = code.replace(
  '<div className="flex items-start gap-4">\n                <div className="bg-white dark:bg-zinc-900 p-3 shadow-sm border border-zinc-100 dark:border-zinc-800">\n                  <Mail className="h-5 w-5 text-zinc-900 dark:text-white" />\n                </div>\n                <div>\n                  <h4 className="font-bold text-sm uppercase tracking-wider text-zinc-900 dark:text-white mb-1">E-mail</h4>\n                  <p className="text-sm text-zinc-500 dark:text-zinc-400">{content.email}</p>\n                  <p className="text-xs text-zinc-400 dark:text-zinc-500 mt-1">Resposta em até 24h úteis</p>\n                </div>\n              </div>',
  `<a href={\`mailto:\${content.email}\`} className="flex items-start gap-4 hover:opacity-80 transition-opacity">\n                <div className="bg-white dark:bg-zinc-900 p-3 shadow-sm border border-zinc-100 dark:border-zinc-800">\n                  <Mail className="h-5 w-5 text-zinc-900 dark:text-white" />\n                </div>\n                <div>\n                  <h4 className="font-bold text-sm uppercase tracking-wider text-zinc-900 dark:text-white mb-1">E-mail</h4>\n                  <p className="text-sm text-zinc-500 dark:text-zinc-400">{content.email}</p>\n                  <p className="text-xs text-zinc-400 dark:text-zinc-500 mt-1">Resposta em até 24h úteis</p>\n                </div>\n              </a>`
);

code = code.replace(
  '<div className="flex items-start gap-4">\n                <div className="bg-white dark:bg-zinc-900 p-3 shadow-sm border border-zinc-100 dark:border-zinc-800">\n                  <Phone className="h-5 w-5 text-zinc-900 dark:text-white" />\n                </div>\n                <div>\n                  <h4 className="font-bold text-sm uppercase tracking-wider text-zinc-900 dark:text-white mb-1">WhatsApp / Telefone</h4>\n                  <p className="text-sm text-zinc-500 dark:text-zinc-400">{content.phone}</p>\n                  <p className="text-xs text-zinc-400 dark:text-zinc-500 mt-1">{content.businessHours}</p>\n                </div>\n              </div>',
  `<a href={\`https://wa.me/\${settings.whatsappNumber?.replace(/\\D/g, '') || '5511999999999'}\`} target="_blank" rel="noreferrer" className="flex items-start gap-4 hover:opacity-80 transition-opacity">\n                <div className="bg-white dark:bg-zinc-900 p-3 shadow-sm border border-zinc-100 dark:border-zinc-800">\n                  <Phone className="h-5 w-5 text-zinc-900 dark:text-white" />\n                </div>\n                <div>\n                  <h4 className="font-bold text-sm uppercase tracking-wider text-zinc-900 dark:text-white mb-1">WhatsApp / Telefone</h4>\n                  <p className="text-sm text-zinc-500 dark:text-zinc-400">{settings.whatsappNumber || content.phone}</p>\n                  <p className="text-xs text-zinc-400 dark:text-zinc-500 mt-1">{content.businessHours}</p>\n                </div>\n              </a>`
);

code = code.replace(
  '<button \n                type="button"\n                className="w-full bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 font-bold uppercase tracking-wider text-sm py-4 hover:bg-zinc-800 dark:hover:bg-zinc-200 transition-colors"\n              >\n                Enviar Mensagem\n              </button>',
  `<button \n                type="button"\n                onClick={() => {\n                  const text = 'Olá! Gostaria de falar com o atendimento.';\n                  window.open(\`https://wa.me/\${settings.whatsappNumber?.replace(/\\D/g, '') || '5511999999999'}?text=\${encodeURIComponent(text)}\`, '_blank');\n                }}\n                className="w-full bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 font-bold uppercase tracking-wider text-sm py-4 hover:bg-zinc-800 dark:hover:bg-zinc-200 transition-colors"\n              >\n                Enviar Mensagem via WhatsApp\n              </button>`
);

fs.writeFileSync('src/pages/ContatoPage.tsx', code);
